### ISSUE TITLE
Resizing not working with X scrolling

### ISSUE THREAD

**Issue by vyruz1986** [Silvacom/colResize#4]
Hi, I've been trying to get this plugin to work with an X-scrolling datatable, but so far I've been unsuccessful.  
I asumed I need to set the `"tableWidthFixed": false` in the options, but this didn't change much.  
I made a quick JSFiddle to show you where I'm at, the resize cursor is appearing, and if you click and drag there is movement, but the columns are not really resizing:
http://jsfiddle.net/kzgq1L25/6/

Thanks for taking a look at this, and thanks for this plugin in general!

**Comment by dykstrad** [comment]
The issue is that the container that the table is in, doesn't allow the table to be larger than it's width. Not sure how to make it work in JSFiddle as we don't have control over the container. But if you put the table in a container that has overflow-x  set to scroll or auto, it should work.

**Comment by dykstrad** [comment]
@vyruz1986 Did you make any progress on this issue?

**Comment by dykstrad** [comment]
@vyruz1986 I have added to explanation to the read me about how to get variable width tables to work. If you are still having troubles with this let me know and I will help you however I can.

**Comment by StephaniesHusband** [comment]
@dykstrad Still unable to get this to work with hidden/not visible columns. :(

**Comment by BurcinTufekci** [comment]
I have a datatable.And I have this problem.İf the problem solved please help me.
