### ISSUE TITLE
colResize not working with ColReorder and ColVis

### ISSUE THREAD

**Issue by ChrisLaforet** [Silvacom/colResize#5]
Hi, I am using Datatables 1.10 and found a reference to this project on DataTables.net.  I pulled down the js and have been trying to get it to work but no luck.  Are there any known "tricks" that need to be done to permit it to work with ColReorder and ColVis?  My table is not autosizing and does not have scrollbars....  I am really holding out hope that colResize will do the trick!  Thanks for any assistance you might be able to provide.

**Comment by dykstrad** [comment]
Your setup or CSS maybe throwing off the plugin. Can you show me how you are using the plug in? I know for non-fixed table widths it requires that the table is placed in a container that will allow the table to resize, often with an overflow-x: auto set. I will try to help you as best I can.

**Comment by ChrisLaforet** [comment]
Thanks for your offer to assist.  A funny thing happened – I started to pull together a trivial case for you to see and everything worked perfectly.  I was able to go back to my original project and get the resize working properly.

Thanks for working on this well-needed project!

-Chris

**Comment by omerman** [comment]
After wrapping the table with a div that has overflow-x: auto, it worked for me as well.
very helpful, thanks!

**Comment by dykstrad** [comment]
@omerman So you have a table with fixedWidth set to false wrapped in a div with overflow-x: auto, and the columns are re-sizing as expected. This doesn't solve the ColVis issue where a hidden column breaks the column resizing correct?

**Comment by dykstrad** [comment]
I have added a comment to the read me to explain more about what needs to be done in order to have variable width tables work. I have also just release a new version that fixes some of the bugs integrating with the ColVis plugin and FixedColumns plug in. Please check it out and let me know if there is anything else I can do to help.

**Comment by omerman** [comment]
Works perfectly now. thanks :)
I've also checked the overflow-x again, and I'm not sure it's needed anymore, I think your fix also covered it, worth double checking though.

**Comment by dykstrad** [comment]
If you want the table to expand, I am quite sure you will still need to
make sure the table is in a container that allows it to overflow, if you
want the table to go past the outer bounds that is.

**Comment by the86freak** [comment]
With the latest version I have a problem with ColVis. (also with older versions, testes with 0.0.8)

After a column is made unvisible, all the columns 'after' that column, are not resizable anymore. Those 'before' are.
http://jsfiddle.net/The86Freak/3h7k25fh/96/

Any idea where I can have a look and fix it? (Not that my PR had some side-effects...)
