### ISSUE TITLE
No resize with an hidden column

### ISSUE THREAD

**Issue by bsitruk** [Silvacom/colResize#6]
Set the "visible" property to false on a column and the resize won't work.
Any idea to fix that ?

**Comment by omerman** [comment]
A NOT working example:  http://jsfiddle.net/bjsk18dt/1/

**Comment by dykstrad** [comment]
Sorry for the delay, Thank you for the example. I will look into this as soon as I can.

**Comment by dykstrad** [comment]
Seems to be a problem with any columns after the column that is hidden, very strange. I am looking into this as we speak and will let you know when it is fixed.

**Comment by omerman** [comment]
Okay, thanks! :)

**Comment by dykstrad** [comment]
I just updated the ColResize Plugin, it has a patch for ColVis so that the columns resize properly after a column is made invisible. I also made it work better with the3 FixedColumns plugin. Let me know if you have any more issues.

**Comment by cj-egidijus-vaisnora** [comment]
Hi,

It looks like that js file is not updated in repository with this feature yet or I am missing something?

Thanks,
Egidijus

**Comment by dykstrad** [comment]
oops, I updated it in the example but not in the main code base. Will update right away. Thanks

**Comment by dykstrad** [comment]
Done, should be fixed

**Comment by cj-egidijus-vaisnora** [comment]
Is it recommended to use ColVis plugin from this site?

**Comment by dykstrad** [comment]
No, use the plugin from the DataTables website. I only included it for the examples.

**Comment by StephaniesHusband** [comment]
@vaisegid Did you get this working? I am still seeing behavior with ColResize 0.0.8

**Comment by cj-egidijus-vaisnora** [comment]
Yes I get it working but with my patch. Just happened so that at the same time as dykstrad I wrote my version of patch which satisfied me. I did not check if dykstrad patch is working for me. 
I can drop it to you if you wish.

**Comment by StephaniesHusband** [comment]
yes, that'd be great.  dykstrad responded to say he was going to take a
look at it but I may need it sooner than later.

**Comment by cj-egidijus-vaisnora** [comment]
I have tried to push branch with a patch but seems I am not granted to do this. How should I deliver it?

**Comment by dykstrad** [comment]
Make a pull request and I will look at applying it To a patched release.

**Comment by cj-egidijus-vaisnora** [comment]
I have patched 0.0.5 version. Is it possible to make pull request to historical version?
